/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Advanced Filter");
gchar *s = N_("Action");
gchar *s = N_("Filter in-place");
gchar *s = N_("Copy to a new location");
gchar *s = N_("Copy to a new sheet");
gchar *s = N_("Copy to a new workbook");
gchar *s = N_("List range:     ");
gchar *s = N_("Criteria range:");
gchar *s = N_("Copy to:        ");
gchar *s = N_("Unique records only");
