/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Advanced Filter");
gchar *s = N_("Action");
gchar *s = N_("_Filter in-place");
gchar *s = N_("_Copy to a new location");
gchar *s = N_("Copy to a new _sheet");
gchar *s = N_("Copy to a new _workbook");
gchar *s = N_("C_riteria range:");
gchar *s = N_("C_opy to:        ");
gchar *s = N_("_List range:     ");
gchar *s = N_("_Unique records only");
