/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Auto Correct");
gchar *s = N_("Correct _TWo INitial CApitals                           ");
gchar *s = N_("_Exceptions...");
gchar *s = N_("Capitalize _first letter of sentence");
gchar *s = N_("Capitalize _names of days");
gchar *s = N_("Correct accidental use of _cAPS LOCK key");
gchar *s = N_("_Replace text when typed");
gchar *s = N_("Re_place:");
gchar *s = N_("_With:");
