/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Gnumeric: Autoformat");
gchar *s = N_("List with categories, click on a category to see it's templates");
gchar *s = N_("Category");
gchar *s = N_("Templates");
gchar *s = N_("Show gridlines in previews");
gchar *s = N_("Create a new template");
gchar *s = N_("New...");
gchar *s = N_("Edit the currently selected template");
gchar *s = N_("Edit...");
gchar *s = N_("Remove the currently selected template");
gchar *s = N_("Remove");
gchar *s = N_("Show more options and information");
gchar *s = N_("More >>");
gchar *s = N_("Template Information");
gchar *s = N_("Name :");
gchar *s = N_("Author :");
gchar *s = N_("Category :");
gchar *s = N_("Description :");
gchar *s = N_("The group/individual that made the template");
gchar *s = N_("The category this template belongs to");
gchar *s = N_("Name of template");
gchar *s = N_("A short description of the template");
gchar *s = N_("Apply");
gchar *s = N_("_Number");
gchar *s = N_("_Border");
gchar *s = N_("_Font");
gchar *s = N_("_Patterns");
gchar *s = N_("_Alignment");
gchar *s = N_("_Dimensions");
