/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("AutoCorrect Exceptions");
gchar *s = N_("_Do not capitalize after:");
gchar *s = N_("_Add");
gchar *s = N_("_Remove");
gchar *s = N_("_First Letter");
gchar *s = N_("Do _not correct:");
gchar *s = N_("_Add");
gchar *s = N_("_Remove");
gchar *s = N_("_INitial CApitals");
