/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Gnumeric: Autoformat");
gchar *s = N_("Apply _Number Formats");
gchar *s = N_("Apply _Borders");
gchar *s = N_("Apply _Fonts");
gchar *s = N_("Apply _Patterns");
gchar *s = N_("Apply _Alignment");
gchar *s = N_("_Show Gridlines");
gchar *s = N_("_New...");
gchar *s = N_("_Edit...");
gchar *s = N_("_Remove Current");
gchar *s = N_("_Category");
gchar *s = N_("The current category");
gchar *s = N_("_Preview");
gchar *s = N_("A short description of the template");
gchar *s = N_("The category this template belongs to");
gchar *s = N_("The group/individual that made the template");
gchar *s = N_("Name of template");
gchar *s = N_("Name :");
gchar *s = N_("Author :");
gchar *s = N_("Category :");
gchar *s = N_("Description :");
gchar *s = N_("_Template Details");
