/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("AutoCorrect Exceptions");
gchar *s = N_("Do not capitalize after:");
gchar *s = N_("Add");
gchar *s = N_("Remove");
gchar *s = N_("First Letter");
gchar *s = N_("Do not correct:");
gchar *s = N_("Add");
gchar *s = N_("Remove");
gchar *s = N_("INitial CApitals");
