/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Auto Save");
gchar *s = N_("_Automatic Save Every");
gchar *s = N_("_Prompt Before Saving");
gchar *s = N_("_minutes");
