/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Sort...");
gchar *s = N_("Selection has");
gchar *s = N_("A header");
gchar *s = N_("Sort");
gchar *s = N_("Rows");
gchar *s = N_("Columns");
gchar *s = N_("Add");
gchar *s = N_("Remove");
