/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Delete cells");
gchar *s = N_("Delete");
gchar *s = N_("Shift cells _left");
gchar *s = N_("Shift cells _up");
gchar *s = N_("Delete _row(s)");
gchar *s = N_("Delete _column(s)");
