/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Zoom");
gchar *s = N_("Magnification");
gchar *s = N_("20_0 %");
gchar *s = N_("_100 %");
gchar *s = N_("_75 %");
gchar *s = N_("_50 %");
gchar *s = N_("_25%");
gchar *s = N_("_Fit Selection %");
gchar *s = N_("_Custom");
gchar *s = N_("%");
gchar *s = N_("Sheets");
