/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Gnumeric : Importing structured text");
gchar *s = N_("Data type and number of lines");
gchar *s = N_("Select the structure of the text that most closely matches the data. Separated means that the each column is separated by a 'separation' character and fixed width means that you can define the width of each column yourself. You should also select what part of the data you want to import by adjusting the from and to line.");
gchar *s = N_("Original data type");
gchar *s = N_("_Separated");
gchar *s = N_("Fixed wi_dth");
gchar *s = N_("Fr_om line :");
gchar *s = N_("_To line : ");
gchar *s = N_("Number of lines to import");
gchar *s = N_("Example");
gchar *s = N_("Separation customization");
gchar *s = N_("Select the separators that appear in the text (you can choose multiple separators if desired and also enter a custom one). You may choose the string indicator and wether you want to see two successive separators as one aswell. Changes will reflect in the example below.");
gchar *s = N_("Separators");
gchar *s = N_("C_ustom");
gchar *s = N_("H_yphen (-)");
gchar *s = N_("S_pace");
gchar *s = N_("Ta_b");
gchar *s = N_("Ban_g (!)");
gchar *s = N_("_Colon (:)");
gchar *s = N_("Co_mma (,)");
gchar *s = N_("P_ipe (|)");
gchar *s = N_("Semicolo_n (;)");
gchar *s = N_("Slas_h (/)");
gchar *s = N_("Misc");
gchar *s = N_("S_ee two separators as one");
gchar *s = N_("Te_xt indicator : ");
gchar *s = N_("\"\n"
              "'\n"
              "`\n"
              "");
gchar *s = N_("\"");
gchar *s = N_("Example");
gchar *s = N_("Fixed width customization");
gchar *s = N_("Customize the columns using the add/remove buttons or the mouse : left click to create a new column, right click on a colum border to delete an existing column and hold the left mouse button on a column border and drag to resize a column.");
gchar *s = N_("Columns");
gchar *s = N_("Column");
gchar *s = N_("End");
gchar *s = N_("Co_lumn end : ");
gchar *s = N_("_Add");
gchar *s = N_("_Remove");
gchar *s = N_("Example");
gchar *s = N_("Column formatting");
gchar *s = N_("Select the format for each column. You can click in the column list on the left to select a column, or you can click in the preview. You can then enter a custom format or select one from the list on the right.");
gchar *s = N_("Per column formatting");
gchar *s = N_("Column");
gchar *s = N_("Format");
gchar *s = N_("_Format :");
gchar *s = N_("label8");
gchar *s = N_("Example");
gchar *s = N_("Finish");
gchar *s = N_("You have successfully finished the customization process.\n"
              "\n"
              "Please press finish.");
