/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Gnumeric : Exporting structured text");
gchar *s = N_("Choose sheets to export");
gchar *s = N_("Please select which sheets you want to export from the current workbook. They will be exported in the same order as in the export list.");
gchar *s = N_("label2");
gchar *s = N_("label3");
gchar *s = N_("Available sheets");
gchar *s = N_("Sheets to export");
gchar *s = N_("Add ->");
gchar *s = N_("<- Remove");
gchar *s = N_("Add all ->");
gchar *s = N_("<- Remove all");
gchar *s = N_("Choose export formatting");
gchar *s = N_("Customize the export format. The line terminator is the character sequence used for terminating a line in the text file. Wether the quote character is placed around cells depends on the value choosen for quoting.");
gchar *s = N_("Line termination :");
gchar *s = N_("Unix (linefeed)\n"
              "Macintosh (carriage return)\n"
              "Windows (carriage return + linefeed)\n"
              "");
gchar *s = N_("Separator :");
gchar *s = N_("\"\n"
              "'\n"
              "`\n"
              "");
gchar *s = N_("\"");
gchar *s = N_("Automatic (puts quotes where needed)\n"
              "Always\n"
              "Never\n"
              "");
gchar *s = N_("Quoting :");
gchar *s = N_("Quote character :");
gchar *s = N_("Space\n"
              "Tab\n"
              "Bang (!)\n"
              "Colon (:)\n"
              "Comma (,)\n"
              "Hyphen (-)\n"
              "Pipe (|)\n"
              "Semicolon (;)\n"
              "Slash (/)\n"
              "Custom\n"
              "");
