/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("Font:");
gchar *s = N_("Font style:");
gchar *s = N_("Size:");
gchar *s = N_("Preview");
gchar *s = N_("AaBbCcDdEeJj12345");
gchar *s = N_("label8");
gchar *s = N_("label7");
gchar *s = N_("label9");
