/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Function Selector");
gchar *s = N_("Function _Categories");
gchar *s = N_("Function _Names");
gchar *s = N_("place holder no need to translate");
gchar *s = N_("place holder no need to translate");
