/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Import");
gchar *s = N_("Choose an import filter for loading the file:");
gchar *s = N_("label2");
