/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Insert cells");
gchar *s = N_("Insert");
gchar *s = N_("_Shift cells right");
gchar *s = N_("Shift cells _down");
gchar *s = N_("Insert _row(s)");
gchar *s = N_("Insert _column(s)");
