/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Define Name");
gchar *s = N_("Names in workbook:");
gchar *s = N_("Add");
gchar *s = N_("Delete");
gchar *s = N_("Refers to:");
