/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("_Add");
gchar *s = N_("_Delete");
gchar *s = N_("_Update");
gchar *s = N_("Define Name");
gchar *s = N_("Name : ");
gchar *s = N_("Scope :");
gchar *s = N_("Expression : ");
