/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Gnumeric Plugin Manager");
gchar *s = N_("Plugin Title");
gchar *s = N_("File name:");
gchar *s = N_("File size:");
gchar *s = N_("Compiled on:");
gchar *s = N_("Description:");
gchar *s = N_("Add");
gchar *s = N_("Remove");
