/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window2");
gchar *s = N_("Orientation");
gchar *s = N_("Por_trait");
gchar *s = N_("_Landscape");
gchar *s = N_("Scale");
gchar *s = N_("_Adjust to:");
gchar *s = N_("_Fit to:");
gchar *s = N_("% of normal size");
gchar *s = N_("page(s) wide by");
gchar *s = N_("tall");
gchar *s = N_("Fi_rst page number:");
gchar *s = N_("_Print");
gchar *s = N_("Print previe_w");
gchar *s = N_("_Options");
gchar *s = N_("Page");
gchar *s = N_("_Top:");
gchar *s = N_("He_ader:");
gchar *s = N_("_Bottom:");
gchar *s = N_("_Footer");
gchar *s = N_("Center on page");
gchar *s = N_("_Horizontally");
gchar *s = N_("_Vertically");
gchar *s = N_("_Left:");
gchar *s = N_("_Right");
gchar *s = N_("Paper _size:");
gchar *s = N_("_Print");
gchar *s = N_("Print previe_w");
gchar *s = N_("_Options");
gchar *s = N_("Margins");
gchar *s = N_("sample goes here");
gchar *s = N_("Header");
gchar *s = N_("Customize _header");
gchar *s = N_("Customize _footer");
gchar *s = N_("Footer:");
gchar *s = N_("sample goes here");
gchar *s = N_("_Print");
gchar *s = N_("Print previe_w");
gchar *s = N_("_Options");
gchar *s = N_("Headers and footers");
gchar *s = N_("Print _area:");
gchar *s = N_("Titles to print");
gchar *s = N_("_Columns to repeat on the left side:");
gchar *s = N_("_Rows to repeat on the upper region:");
gchar *s = N_("Print");
gchar *s = N_("Row and co_lumn headings");
gchar *s = N_("Co_mments");
gchar *s = N_("_Grid lines");
gchar *s = N_("_Black and white");
gchar *s = N_("Page order");
gchar *s = N_("_Down, then right");
gchar *s = N_("R_ight, then down");
gchar *s = N_("_Print");
gchar *s = N_("Print previe_w");
gchar *s = N_("_Options");
gchar *s = N_("Page");
