/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window2");
gchar *s = N_("Orientation");
gchar *s = N_("Vertical");
gchar *s = N_("Horizontal");
gchar *s = N_("Scale");
gchar *s = N_("Adjust to");
gchar *s = N_("Adjust to");
gchar *s = N_("% of the original size");
gchar *s = N_("pages wider by ");
gchar *s = N_("pages of height");
gchar *s = N_("Paper size:");
gchar *s = N_("First page number:");
gchar *s = N_("Print");
gchar *s = N_("Print preview");
gchar *s = N_("Options");
gchar *s = N_("Page");
gchar *s = N_("Superior:");
gchar *s = N_("Header:");
gchar *s = N_("Lower:");
gchar *s = N_("Footer");
gchar *s = N_("Center on page");
gchar *s = N_("Horizontally");
gchar *s = N_("Vertically");
gchar *s = N_("Left:");
gchar *s = N_("Right:");
gchar *s = N_("Print");
gchar *s = N_("Print preview");
gchar *s = N_("Options");
gchar *s = N_("Margins");
gchar *s = N_("sample goes here");
gchar *s = N_("Header");
gchar *s = N_("Footer:");
gchar *s = N_("sample goes jere");
gchar *s = N_("Print");
gchar *s = N_("Print preview");
gchar *s = N_("Options");
gchar *s = N_("Headers and footers");
gchar *s = N_("Print region:");
gchar *s = N_("Titles to print");
gchar *s = N_("Rows to repear on the left side:");
gchar *s = N_("Rows to repeat on the upper region:");
gchar *s = N_("Print");
gchar *s = N_("Division lines");
gchar *s = N_("Black and white");
gchar *s = N_("Titles of rows and columns.");
gchar *s = N_("Comments");
gchar *s = N_("Page order");
gchar *s = N_("Down, then right");
gchar *s = N_("RIght, then down");
gchar *s = N_("Print");
gchar *s = N_("Print preview");
gchar *s = N_("Options");
gchar *s = N_("Page");
