/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Add Constraint");
gchar *s = N_("_Left Hand Side:");
gchar *s = N_("_Type:");
gchar *s = N_("_Right Hand Side:");
gchar *s = N_("Add  ");
gchar *s = N_("Change Constraint");
gchar *s = N_("_Left Hand Side:");
gchar *s = N_("_Type:");
gchar *s = N_("_Right Hand Side:");
gchar *s = N_("Gnumeric Solver Parameters");
gchar *s = N_("_Set Target Cell:       ");
gchar *s = N_("                         ");
gchar *s = N_("Equal To:");
gchar *s = N_("_Max");
gchar *s = N_("M_in");
gchar *s = N_("B_y Changing Cells: ");
gchar *s = N_("                         ");
gchar *s = N_("Subject to the Constraints:");
gchar *s = N_("_Add");
gchar *s = N_("_Change");
gchar *s = N_("_Delete");
gchar *s = N_("Solve");
gchar *s = N_("Options...");
gchar *s = N_("Reports:");
gchar *s = N_("_Answer");
gchar *s = N_("_Sensitivity");
gchar *s = N_("_Limits");
gchar *s = N_("_Keep Solver Solution");
gchar *s = N_("_Restore Original Values");
