/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Add Constraint");
gchar *s = N_("Left Hand Side:");
gchar *s = N_("Type:");
gchar *s = N_("Right Hand Side:");
gchar *s = N_("Add  ");
gchar *s = N_("Change Constraint");
gchar *s = N_("Left Hand Side:");
gchar *s = N_("Type:");
gchar *s = N_("Right Hand Side:");
gchar *s = N_("Gnumeric Solver Parameters");
gchar *s = N_("Set Target Cell:       ");
gchar *s = N_("                         ");
gchar *s = N_("Equal To:");
gchar *s = N_("Max");
gchar *s = N_("Min");
gchar *s = N_("By Changing Cells: ");
gchar *s = N_("                         ");
gchar *s = N_("Subject to the Constraints:");
gchar *s = N_("Add");
gchar *s = N_("Change");
gchar *s = N_("Delete");
gchar *s = N_("Solve");
gchar *s = N_("Options...");
gchar *s = N_("Reports:");
gchar *s = N_("Answer");
gchar *s = N_("Sensitivity");
gchar *s = N_("Limits");
gchar *s = N_("Keep Solver Solution");
gchar *s = N_("Restore Original Values");
