/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Solver Options");
gchar *s = N_("Assume _Linear Model");
gchar *s = N_("Assume _Non-Negative");
