/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Summary");
gchar *s = N_("Title");
gchar *s = N_("Author");
gchar *s = N_("Category");
gchar *s = N_("Keywords");
gchar *s = N_("Manager");
gchar *s = N_("Document Summary Information\n"
              "");
gchar *s = N_("Comments");
gchar *s = N_("Company");
