/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Scrollbars");
gchar *s = N_("_Horizontal Scrollbar");
gchar *s = N_("_Vertical Scrollbar");
gchar *s = N_("Notebook");
gchar *s = N_("_Tabs");
gchar *s = N_("View");
