# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

define "page5" A90
define "page1" A11
define "page2" A30
define "page3" A50
define "page4" A71
leftstring A1 = "This is a brief sc tutorial, best run in a 24-line window."
leftstring A2 = "Type 'q' to exit, ^Z to suspend (w/ Job Control)."
leftstring A3 = "^G interrupts a command."
leftstring A5 = "Cells are named by their column and row number.  For example,"
leftstring A6 = "Cell A6"
leftstring B6 = "Cell B6"
leftstring C6 = "Cell C6"
leftstring A7 = "Cell A7"
leftstring A8 = "Cell A8"
leftstring C8 = "Cell C8"
leftstring A9 = "Cells range from A0 to ZZ(some number depending on free memory)."
leftstring A10 = "Cells can also be named by the user.  See 'range names' in the manual."
leftstring page1 = "You can move the cursor a couple of different ways:"
leftstring B12 = "^n, j and the <DOWN> arrow key go down"
leftstring B13 = "^p, k and the <UP> arrow key go up"
leftstring B14 = "^b, h and the <LEFT> arrow key go left"
leftstring B15 = "^f, l and the <RIGHT> arrow key go right"
leftstring B16 = "You can go directly to a cell by typing 'g' and the cell name. "
leftstring B17 = "'g c6' will take you to cell c6."
leftstring A19 = "Cells can contain numbers, formulas, or text."
leftstring A20 = "Most of the cells on this page contain text."
leftstring C21 = "<Type 'g page2' to continue>"
leftstring A23 = "Cell d23 contains text"
leftstring D23 = "Text "
leftstring A24 = "Cell d24 contains a number"
let D24 = 123.34
leftstring A25 = "Cell d25 contains a formula"
let D25 = D24+88
leftstring A27 = "To see what the cell contains, just move the cursor"
leftstring A28 = "onto the cell.  The contents will show up on line 1 in the brackets."
leftstring page2 = "You can enter data into cells like this:"
leftstring B31 = "'<text' enters left justified text."
leftstring B32 = "'>text' enters right justified text."
leftstring B33 = "'=number' enters a number"
leftstring B34 = "'=formula' enters a formula."
leftstring A36 = "Try duplicating d23 through d25 in e23 though e25."
leftstring A38 = "You erase a cell by typing 'x' with the cursor on the cell."
leftstring C41 = "<Type 'g page3' to continue>"
leftstring A43 = "Here is a typical use for numbers and formulas:"
let A45 = 10.3
let B45 = 1877.5
let C45 = 234.7
let E45 = @sum(A45:C45)
let A46 = 44.56
let B46 = 44.3
let C46 = -3
let E46 = @sum(A46:C46)
let A47 = 88.74
let B47 = 8000
let C47 = -9
let E47 = @sum(A47:C47)
let A48 = 99.2
let B48 = -88
let C48 = -44.6
let E48 = @sum(A48:C48)
let page3 = @sum(A45:A48)
let B50 = @sum(B45:B48)
let C50 = @sum(C45:C48)
let E50 = @sum(A45:C48)
leftstring A52 = "The data is entered in a45 through c48."
leftstring A53 = "Cells a50, b50 and c50 sum their respective columns."
leftstring A54 = "Cells e45, e46, e47, and e48 sum their respective rows."
leftstring A55 = "Cell E50 is a grand total."
leftstring A56 = "Try changing some of the data cells and watch the sums change."
leftstring A58 = "You can also edit cells by putting the cursor on the cell and typing:"
leftstring B59 = "'e' to edit the numeric portion."
leftstring B60 = "'E' to edit the string portion."
leftstring C61 = "<Type 'g page4' to continue>"
leftstring A63 = "Since you are reading this, you know that you can load "
leftstring A64 = "a data base from a file by typing the file name as an"
leftstring A65 = "argument to the program.  You can also load or save a "
leftstring A66 = "data base using the file commands:"
leftstring B68 = "'G file'"
leftstring C68 = "Gets the data from an sc file."
leftstring B69 = "'P file'"
leftstring C69 = "Puts the data from the spreadsheet into a file."
leftstring page4 = "Try 'P foo.sc' to write this to the file foo.sc"
leftstring A72 = "The Get command erases the current spreadsheet.  "
leftstring A73 = "To merge a spreadsheet with the one currently in"
leftstring A74 = "the machine, use:"
leftstring B76 = "'M file'"
leftstring C76 = "Merge the data from a saved sc file."
leftstring A78 = "You can also get human readable versions of the data"
leftstring A79 = "by using the Write command:"
leftstring C81 = "<Type 'g page5' to continue>"
leftstring A83 = "Try 'W tut.txt' for a clear text version of the tutorial."
leftstring A86 = "This is the end of the tutorial.  We have explored"
leftstring A87 = "The basic commands.  Much more detail is available"
leftstring A88 = "in the man page."
leftstring page5 = "To quit this program, type 'q'."
leftstring D92 = "GOOD LUCK!"
