include:
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@release-service-sandbox # <-- instead of @master
  # - component: "gitlab.gnome.org/GNOME/citemplates/release-service@master"
    inputs:
      job-stage: "release"
      dist-job-name: "build-release-tarball"
      tarball-artifact-path: ${TARBALL_ARTIFACT_PATH}

image: ubuntu

stages:
  - "build"
  - "release"

variables:
  TARBALL_ARTIFACT_PATH: ${CI_PROJECT_NAME}-${CI_COMMIT_TAG_MESSAGE}.tar.xz

build-release-tarball:
  stage: "build"
  before_script:
    - DEBIAN_FRONTEND=noninteractive apt update
    - DEBIAN_FRONTEND=noninteractive apt -y install autoconf automake zlib1g-dev libglib2.0-dev libxml2-dev gtk-doc-tools autopoint libtool libbz2-dev libgdk-pixbuf2.0-dev make libgtk-3-dev libgsf-1-dev libgoffice-0-dev libpango1.0-dev libcairo2-dev intltool librsvg2-dev libxslt1-dev
  script:
    - ACVER=`perl -ne '$ep=$1 if /^m4_define.*gnumeric_version_epoch.*\[(\d+)\]/; $ma=$1 if /^m4_define.*gnumeric_version_major.*\[(\d+)\]/; $mi=$1 if /^m4_define.*gnumeric_version_minor.*\[(\S+)\]/; END { print "$ep.$ma.$mi\n"; }' configure.ac`
    - echo ${ACVER}
    - echo ${TARBALL_ARTIFACT_PATH}
    - ./autogen.sh --disable-dependency-tracking
    - make -j4
    - make dist
    - gunzip <"${CI_PROJECT_NAME}-${ACVER}.tar.gz" | xz > ${TARBALL_ARTIFACT_PATH}
    - rm -f "${CI_PROJECT_NAME}-${ACVER}.tar.gz" "${CI_PROJECT_NAME}-${ACVER}.tar.bz2"
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: "always"
    paths:
      - "${TARBALL_ARTIFACT_PATH}"
