#undef PACKAGE
#undef GETTEXT_PACKAGE
#undef VERSION
#undef GNUMERIC_VERSION
#undef GNUMERIC_PREFIX
#undef GNUMERIC_LOCALE_DIR

#undef HAVE_LC_MESSAGES

#undef WITH_BONOBO
#undef WITH_PYGTK
#undef ENABLE_EVOLUTION

#undef HAVE_FINITE
#undef HAVE_ISFINITE
#undef HAVE_IEEEFP_H
#undef HAVE_IEEE754_H
#undef WITH_LONG_DOUBLE
#undef MUST_PROTOTYPE_STRTOLD

@BOTTOM@
