#!/bin/sh
# Run this to generate all the initial makefiles, etc.

PKG_NAME="Gnumeric"

REQUIRED_AUTOMAKE_VERSION=1.7.2
REQUIRED_LIBTOOL_VERSION=1.4.3

# We use the XGETTEXT_KEYWORDS variable, thus we require:
REQUIRED_INTLTOOL_VERSION=0.29
# ... well, to be true, we need 0.34, but it's too early to require it.
# See below for details.

USE_GNOME2_MACROS=1
USE_COMMON_DOC_BUILD=yes

srcdir=`dirname $0`
test -z "$srcdir" && srcdir=.

# The traslators only need to set up the po-functions/ directory:
if test "x$TRANSL_ONLY" = x1; then
  GNM_NOCONFIGURE=1
  print_bold=echo
else
  print_bold=printbold

  (test -f $srcdir/configure.in \
    && test -d $srcdir/src \
    && test -f $srcdir/src/gnumeric.h) || {
      echo -n "**Error**: Directory "\`$srcdir\'" does not look like the"
      echo " top-level gnumeric directory"
      exit 1
  }

  ifs_save="$IFS"; IFS=":"
  for dir in $PATH ; do
    IFS="$ifs_save"
    test -z "$dir" && dir=.
    if test -f $dir/gnome-autogen.sh ; then
      gnome_autogen="$dir/gnome-autogen.sh"
      gnome_datadir=`echo $dir | sed -e 's,/bin$,/share,'`
      break
    fi
  done

  if test -z "$gnome_autogen" ; then
    echo "You need to install the gnome-common module and make"
    echo "sure the gnome-autogen.sh script is in your \$PATH."
    exit 1
  fi

  GNOME_DATADIR="$gnome_datadir"

  # Dont't run configure yet, ...
  GNM_NOCONFIGURE=$NOCONFIGURE
  NOCONFIGURE=1
  . $gnome_autogen

fi

# We want intltool 0.34.
# intltoolize 0.34 brings its own copy of Makefile.in.in, instead of the
# complicated system of patches.  And it doesn't have "po/" hardwired in
# the .po.pox rule.
# In the meantime, we will force our own copy:
#
$print_bold "Creating po/Makefile.in.in."
rm -f $srcdir/po/Makefile.in.in $srcdir/po-functions/Makefile.in.in
cp $srcdir/po/Makefile.in.in.own $srcdir/po/Makefile.in.in

$print_bold "Creating po-functions/Makefile.in.in."
rm -f $srcdir/po-functions/Makefile.in.in
sed '/^\(GETTEXT_PACKAGE\|subdir\) =/s/[ 	]*$/-functions/
/^GETTEXT_PACKAGE =/a\
XGETTEXT_KEYWORDS = --keyword --keyword=F_
' $srcdir/po/Makefile.in.in >$srcdir/po-functions/Makefile.in.in

$print_bold "Creating po-functions/POTFILES.{in,skip}."
rm -f $srcdir/po-functions/POTFILES.in $srcdir/po-functions/POTFILES.skip
for file in POTFILES.in POTFILES.skip; do
  echo "# Generated by configure; do not edit." >$srcdir/po-functions/$file
done
test -f $srcdir/po/POTFILES.skip && \
	sed <$srcdir/po/POTFILES.skip -e '/^#/d' >>$srcdir/po-functions/POTFILES.skip
awk '
/^[^#]/ {
  skip = (/^((schemas|templates)\/.*|[^\/]*)\.in$/ || /\.(glade|xml)(\.in)?$/)
  print >>("'$srcdir'/po-functions/POTFILES." (skip ? "skip" : "in"))
}
' $srcdir/po/POTFILES.in

# ... and then proceed.
if test "x$GNM_NOCONFIGURE" = x; then
    printbold Running $srcdir/configure $conf_flags "$@" ...
    $srcdir/configure $conf_flags "$@" \
        && echo Now type \`make\' to compile $PKG_NAME || exit 1
fi
