/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define lpt_yyconst const
#else
#define lpt_yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN lpt_yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((lpt_yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE lpt_yyrestart( lpt_yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct lpt_yy_buffer_state *YY_BUFFER_STATE;

extern int lpt_yyleng;
extern FILE *lpt_yyin, *lpt_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		lpt_yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the lpt_yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define lpt_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up lpt_yytext. */ \
		*lpt_yy_cp = lpt_yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		lpt_yy_c_buf_p = lpt_yy_cp = lpt_yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up lpt_yytext again */ \
		} \
	while ( 0 )

#define unput(c) lpt_yyunput( c, lpt_yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int lpt_yy_size_t;


struct lpt_yy_buffer_state
	{
	FILE *lpt_yy_input_file;

	char *lpt_yy_ch_buf;		/* input buffer */
	char *lpt_yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	lpt_yy_size_t lpt_yy_buf_size;

	/* Number of characters read into lpt_yy_ch_buf, not including EOB
	 * characters.
	 */
	int lpt_yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int lpt_yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int lpt_yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int lpt_yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int lpt_yy_fill_buffer;

	int lpt_yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via lpt_yyrestart()), so that the user can continue scanning by
	 * just pointing lpt_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE lpt_yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER lpt_yy_current_buffer


/* lpt_yy_hold_char holds the character lost when lpt_yytext is formed. */
static char lpt_yy_hold_char;

static int lpt_yy_n_chars;		/* number of characters read into lpt_yy_ch_buf */


int lpt_yyleng;

/* Points to current character in buffer. */
static char *lpt_yy_c_buf_p = (char *) 0;
static int lpt_yy_init = 1;		/* whether we need to initialize */
static int lpt_yy_start = 0;	/* start state number */

/* Flag which is used to allow lpt_yywrap()'s to do buffer switches
 * instead of setting up a fresh lpt_yyin.  A bit of a hack ...
 */
static int lpt_yy_did_buffer_switch_on_eof;

void lpt_yyrestart YY_PROTO(( FILE *input_file ));

void lpt_yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void lpt_yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE lpt_yy_create_buffer YY_PROTO(( FILE *file, int size ));
void lpt_yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void lpt_yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void lpt_yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER lpt_yy_flush_buffer( lpt_yy_current_buffer )

YY_BUFFER_STATE lpt_yy_scan_buffer YY_PROTO(( char *base, lpt_yy_size_t size ));
YY_BUFFER_STATE lpt_yy_scan_string YY_PROTO(( lpt_yyconst char *lpt_yy_str ));
YY_BUFFER_STATE lpt_yy_scan_bytes YY_PROTO(( lpt_yyconst char *bytes, int len ));

static void *lpt_yy_flex_alloc YY_PROTO(( lpt_yy_size_t ));
static void *lpt_yy_flex_realloc YY_PROTO(( void *, lpt_yy_size_t ));
static void lpt_yy_flex_free YY_PROTO(( void * ));

#define lpt_yy_new_buffer lpt_yy_create_buffer

#define lpt_yy_set_interactive(is_interactive) \
	{ \
	if ( ! lpt_yy_current_buffer ) \
		lpt_yy_current_buffer = lpt_yy_create_buffer( lpt_yyin, YY_BUF_SIZE ); \
	lpt_yy_current_buffer->lpt_yy_is_interactive = is_interactive; \
	}

#define lpt_yy_set_bol(at_bol) \
	{ \
	if ( ! lpt_yy_current_buffer ) \
		lpt_yy_current_buffer = lpt_yy_create_buffer( lpt_yyin, YY_BUF_SIZE ); \
	lpt_yy_current_buffer->lpt_yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (lpt_yy_current_buffer->lpt_yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *lpt_yyin = (FILE *) 0, *lpt_yyout = (FILE *) 0;
typedef int lpt_yy_state_type;
#define YY_FLEX_LEX_COMPAT
extern int lpt_yylineno;
int lpt_yylineno = 1;
extern char lpt_yytext[];


static lpt_yy_state_type lpt_yy_get_previous_state YY_PROTO(( void ));
static lpt_yy_state_type lpt_yy_try_NUL_trans YY_PROTO(( lpt_yy_state_type current_state ));
static int lpt_yy_get_next_buffer YY_PROTO(( void ));
static void lpt_yy_fatal_error YY_PROTO(( lpt_yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up lpt_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	lpt_yytext_ptr = lpt_yy_bp; \
	lpt_yyleng = (int) (lpt_yy_cp - lpt_yy_bp); \
	lpt_yy_hold_char = *lpt_yy_cp; \
	*lpt_yy_cp = '\0'; \
	if ( lpt_yyleng + lpt_yy_more_offset >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	lpt_yy_flex_strncpy( &lpt_yytext[lpt_yy_more_offset], lpt_yytext_ptr, lpt_yyleng + 1 ); \
	lpt_yyleng += lpt_yy_more_offset; \
	lpt_yy_prev_more_offset = lpt_yy_more_offset; \
	lpt_yy_more_offset = 0; \
	lpt_yy_c_buf_p = lpt_yy_cp;

#define YY_NUM_RULES 25
#define YY_END_OF_BUFFER 26
static lpt_yyconst short int lpt_yy_acclist[173] =
    {   0,
       22,   22,   26,   24,   25,    5,   24,   25,    5,   25,
       21,   24,   25,   15,   24,   25,   24,   25,   11,   12,
       24,   25,   22,   24,   25,   22,   24,   25,   23,   24,
       25,   21,   24,   25,   21,   24,   25,    1,   24,   25,
       21,   24,   25,   21,   24,   25,   21,   24,   25,   21,
       24,   25,   21,   24,   25,   21,   24,   25,    4,   25,
        2,   25,    3,    4,   25,    5,   21,   20,   15,   12,
       11,   12,   22,   23,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,    8,   21,   21,   12,
       21,   20,   16,   21,   21,   10,   21,   16,   21,   16,

       21,    7,   21,    6,   21,   21,   21,   18,   21,    8,
       21,   21,   21,   13,   14,   21,   19,   21,   21,   21,
       21,   21,   21,   17,   21,   21,   21,   21,    9,   21,
       21,   21,   21,   21,   17,   21,   21,   21,   16,   21,
        9,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       16,   21,   16,   21,   21,    7,   21,   21,    6,   21,
       21,   16,   21,   16,   21,    7,   21,    6,   21,   13,
        8,   17
    } ;

static lpt_yyconst short int lpt_yy_accept[139] =
    {   0,
        1,    2,    3,    3,    3,    4,    6,    9,   11,   14,
       17,   19,   23,   26,   29,   32,   35,   38,   41,   44,
       47,   50,   53,   56,   59,   61,   63,   66,   67,   67,
       68,   69,   70,   70,   71,   71,   73,   73,   74,   75,
       76,   77,   78,   79,   80,   81,   82,   83,   84,   85,
       86,   87,   89,   90,   90,   90,   91,   92,   93,   95,
       96,   98,  100,  102,  104,  106,  107,  108,  110,  112,
      113,  114,  115,  117,  118,  119,  120,  121,  122,  123,
      124,  126,  127,  128,  128,  129,  131,  132,  133,  134,
      135,  135,  137,  138,  138,  138,  139,  141,  143,  144,

      145,  146,  147,  148,  149,  149,  150,  150,  150,  151,
      153,  155,  156,  158,  159,  161,  161,  162,  162,  162,
      164,  166,  168,  170,  170,  170,  170,  171,  171,  171,
      172,  172,  172,  172,  172,  172,  173,  173
    } ;

static lpt_yyconst int lpt_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    7,    6,    8,    9,    6,   10,   11,   11,
       10,   10,   10,   10,   10,   10,   10,   12,    6,   13,
       14,   15,    6,    6,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,    6,   26,   27,   28,   29,    6,
        6,   30,   31,   32,   33,    6,    6,   34,   35,   36,
        1,   37,    1,    1,    6,    6,   16,   17,   18,   19,

       20,   21,   22,   23,   24,   25,    6,   26,   27,   28,
       29,    6,    6,   30,   31,   32,   33,    6,    6,   34,
       35,   36,    6,    6,    6,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static lpt_yyconst int lpt_yy_meta[38] =
    {   0,
        1,    2,    2,    2,    2,    3,    2,    2,    3,    3,
        3,    3,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1
    } ;

static lpt_yyconst short int lpt_yy_base[141] =
    {   0,
        0,   21,   36,   43,  265,  266,   42,   46,  252,   48,
       47,   50,  249,  266,  248,   32,   52,  266,   53,   39,
       54,   56,   57,   76,  266,  266,  266,    0,  237,  248,
      266,   68,  231,   69,   80,   83,   90,  266,  266,   66,
      246,   71,   83,   92,   90,   94,   95,  100,   98,  105,
      102,  110,  103,  236,  113,  124,  119,  244,  124,  113,
      243,  125,  126,  130,  131,  135,  136,  242,  241,  137,
      138,  228,  239,  266,  139,  140,  141,  144,  145,  146,
      155,  156,  165,  222,  163,  152,  162,  168,  167,  169,
      231,  236,  172,  215,  222,  177,  233,  232,  101,  173,

      170,  180,  182,  183,  214,  184,  219,  209,  189,  192,
      193,  197,  228,  199,  227,  210,  203,  221,  179,  224,
      223,  222,  221,  200,  199,  198,  266,  205,  199,  266,
      194,  188,  184,  179,  134,  266,  266,  224,   69,   39
    } ;

static lpt_yyconst short int lpt_yy_def[141] =
    {   0,
      137,    1,  138,  138,  137,  137,  139,  139,  140,  137,
      137,  137,  137,  137,  137,  140,  140,  137,  140,  140,
      140,  140,  140,  140,  137,  137,  137,    8,  137,  140,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  137,  137,  137,  140,  137,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      140,  137,  140,  137,  140,  140,  140,  140,  140,  140,
      140,  140,  140,  137,  140,  140,  140,  140,  140,  140,
      137,  140,  140,  137,  137,  140,  140,  140,  140,  140,

      140,  140,  140,  140,  137,  140,  137,  137,  140,  140,
      140,  140,  140,  140,  140,  137,  140,  137,  137,  140,
      140,  140,  140,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,    0,  137,  137,  137
    } ;

static lpt_yyconst short int lpt_yy_nxt[304] =
    {   0,
        6,    7,    8,    7,    7,    9,   10,   10,   11,   12,
       12,    6,   13,   14,   15,    9,    9,    9,    9,    9,
       16,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       17,    9,    9,    9,    9,    9,   18,   19,   26,   27,
       20,   30,   21,   31,   22,   26,   27,   23,   29,   29,
       31,   24,   29,   29,   32,   32,   34,   34,   35,   36,
       36,   40,   41,   31,   31,   31,   44,   31,   31,   37,
       28,   33,   47,   45,   32,   32,   42,   31,   34,   34,
       48,   43,   31,   46,   49,   57,   41,   31,   37,   34,
       34,   35,   36,   36,   31,   50,   55,   55,   59,   56,

       56,   31,   37,   31,   51,   31,   31,   52,   53,   31,
       61,   31,   31,   31,   31,   60,   31,   62,   69,   70,
       71,   31,   56,   56,   31,   63,  110,   65,   64,   66,
       31,   67,   68,   56,   56,   31,   31,   31,   73,   75,
       76,   31,   31,   69,   77,   78,   31,   31,   31,   31,
       31,   31,   31,   79,   80,   31,   31,   31,   86,   81,
       83,   82,   91,   31,  136,   88,   31,   31,   85,   94,
       87,   89,   90,   31,   31,   93,   31,   99,   31,   31,
       31,   31,   98,   31,   31,   92,   96,  100,   31,  106,
      101,   31,  103,   31,   31,   31,  109,   97,  127,  102,

       31,  104,  111,   31,   31,  112,  113,  125,   31,  115,
       31,  135,  134,  127,   31,  117,  122,  114,  123,   97,
      133,  132,  120,  121,   25,   25,   25,  130,  131,  130,
      129,  128,   31,   31,   31,   31,  126,  124,   31,   31,
      119,  118,  116,   31,   31,  108,  107,   31,  105,   95,
       31,   84,   31,   31,   31,   74,   72,   58,   54,   31,
       33,   39,   38,   31,  137,    5,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,

      137,  137,  137
    } ;

static lpt_yyconst short int lpt_yy_chk[304] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    3,
        2,  140,    2,   16,    2,    4,    4,    2,    7,    7,
       20,    2,    8,    8,   10,   10,   11,   11,   12,   12,
       12,   16,   17,   17,   19,   21,   20,   22,   23,   12,
      139,   10,   23,   21,   32,   32,   19,   40,   34,   34,
       23,   19,   42,   22,   24,   40,   24,   24,   34,   35,
       35,   36,   36,   36,   43,   24,   37,   37,   42,   37,

       37,   45,   36,   44,   24,   46,   47,   24,   24,   49,
       44,   48,   99,   51,   53,   43,   50,   45,   52,   53,
       53,   52,   55,   55,   60,   46,   99,   48,   47,   49,
       57,   50,   51,   56,   56,   59,   62,   63,   57,   59,
       60,   64,   65,   66,   62,   63,   66,   67,   70,   71,
       75,   76,   77,   64,   65,   78,   79,   80,   76,   67,
       71,   70,   81,   86,  135,   78,   81,   82,   75,   83,
       77,   79,   80,   87,   85,   82,   83,   87,   89,   88,
       90,  101,   86,   93,  100,   81,   85,   88,   96,   93,
       89,  102,   90,  103,  104,  106,   96,   85,  119,   89,

      109,   90,  100,  110,  111,  101,  102,  117,  112,  104,
      114,  134,  133,  119,  117,  106,  112,  103,  114,  109,
      132,  131,  110,  111,  138,  138,  138,  129,  128,  126,
      125,  124,  123,  122,  121,  120,  118,  116,  115,  113,
      108,  107,  105,   98,   97,   95,   94,   92,   91,   84,
       73,   72,   69,   68,   61,   58,   54,   41,   33,   30,
       29,   15,   13,    9,    5,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  137,  137,  137,  137,

      137,  137,  137
    } ;

static lpt_yy_state_type lpt_yy_state_buf[YY_BUF_SIZE + 2], *lpt_yy_state_ptr;
static char *lpt_yy_full_match;
static int lpt_yy_lp;
#define REJECT \
{ \
*lpt_yy_cp = lpt_yy_hold_char; /* undo effects of setting up lpt_yytext */ \
lpt_yy_cp = lpt_yy_full_match; /* restore poss. backed-over text */ \
++lpt_yy_lp; \
goto find_rule; \
}
static int lpt_yy_more_offset = 0;
static int lpt_yy_prev_more_offset = 0;
#define lpt_yymore() (lpt_yy_more_offset = lpt_yy_flex_strlen( lpt_yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	lpt_yy_more_offset = lpt_yy_prev_more_offset; \
	lpt_yyleng -= lpt_yy_more_offset; \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char lpt_yytext[YYLMAX];
char *lpt_yytext_ptr;
#define INITIAL 0
#define LINECOMMENT 1


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int lpt_yywrap YY_PROTO(( void ));
#else
extern int lpt_yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void lpt_yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef lpt_yytext_ptr
static void lpt_yy_flex_strncpy YY_PROTO(( char *, lpt_yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int lpt_yy_flex_strlen YY_PROTO(( lpt_yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int lpt_yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int lpt_yy_start_stack_ptr = 0;
static int lpt_yy_start_stack_depth = 0;
static int *lpt_yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void lpt_yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void lpt_yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int lpt_yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( lpt_yytext, lpt_yyleng, 1, lpt_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( lpt_yy_current_buffer->lpt_yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( lpt_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( lpt_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, lpt_yyin )) == 0) \
		  && ferror( lpt_yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "lpt_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef lpt_yyterminate
#define lpt_yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) lpt_yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int lpt_yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after lpt_yytext and lpt_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( lpt_yyleng > 0 ) \
		lpt_yy_current_buffer->lpt_yy_at_bol = \
				(lpt_yytext[lpt_yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register lpt_yy_state_type lpt_yy_current_state;
	register char *lpt_yy_cp, *lpt_yy_bp;
	register int lpt_yy_act;




	if ( lpt_yy_init )
		{
		lpt_yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! lpt_yy_start )
			lpt_yy_start = 1;	/* first start state */

		if ( ! lpt_yyin )
			lpt_yyin = stdin;

		if ( ! lpt_yyout )
			lpt_yyout = stdout;

		if ( ! lpt_yy_current_buffer )
			lpt_yy_current_buffer =
				lpt_yy_create_buffer( lpt_yyin, YY_BUF_SIZE );

		lpt_yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		lpt_yy_cp = lpt_yy_c_buf_p;

		/* Support of lpt_yytext. */
		*lpt_yy_cp = lpt_yy_hold_char;

		/* lpt_yy_bp points to the position in lpt_yy_ch_buf of the start of
		 * the current run.
		 */
		lpt_yy_bp = lpt_yy_cp;

		lpt_yy_current_state = lpt_yy_start;
		lpt_yy_current_state += YY_AT_BOL();
		lpt_yy_state_ptr = lpt_yy_state_buf;
		*lpt_yy_state_ptr++ = lpt_yy_current_state;
lpt_yy_match:
		do
			{
			register YY_CHAR lpt_yy_c = lpt_yy_ec[YY_SC_TO_UI(*lpt_yy_cp)];
			while ( lpt_yy_chk[lpt_yy_base[lpt_yy_current_state] + lpt_yy_c] != lpt_yy_current_state )
				{
				lpt_yy_current_state = (int) lpt_yy_def[lpt_yy_current_state];
				if ( lpt_yy_current_state >= 138 )
					lpt_yy_c = lpt_yy_meta[(unsigned int) lpt_yy_c];
				}
			lpt_yy_current_state = lpt_yy_nxt[lpt_yy_base[lpt_yy_current_state] + (unsigned int) lpt_yy_c];
			*lpt_yy_state_ptr++ = lpt_yy_current_state;
			++lpt_yy_cp;
			}
		while ( lpt_yy_base[lpt_yy_current_state] != 266 );

lpt_yy_find_action:
		lpt_yy_current_state = *--lpt_yy_state_ptr;
		lpt_yy_lp = lpt_yy_accept[lpt_yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( lpt_yy_lp && lpt_yy_lp < lpt_yy_accept[lpt_yy_current_state + 1] )
				{
				lpt_yy_act = lpt_yy_acclist[lpt_yy_lp];
					{
					lpt_yy_full_match = lpt_yy_cp;
					break;
					}
				}
			--lpt_yy_cp;
			lpt_yy_current_state = *--lpt_yy_state_ptr;
			lpt_yy_lp = lpt_yy_accept[lpt_yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( lpt_yy_act != YY_END_OF_BUFFER )
			{
			int lpt_yyl;
			for ( lpt_yyl = 0; lpt_yyl < lpt_yyleng; ++lpt_yyl )
				if ( lpt_yytext[lpt_yyl] == '\n' )
					++lpt_yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( lpt_yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
{
  BEGIN LINECOMMENT;
} /* begin skip LINECOMMENT */
	YY_BREAK
case 2:
YY_RULE_SETUP
{
  BEGIN INITIAL;
} /* end skip LINECOMMENT */
	YY_BREAK
case 3:
YY_RULE_SETUP
{
  BEGIN INITIAL;
} /* end skip LINECOMMENT */
	YY_BREAK
case 4:
YY_RULE_SETUP
{
}
	YY_BREAK
case 5:
YY_RULE_SETUP
{
}
	YY_BREAK
case 6:
YY_RULE_SETUP
{
  /* strcpy(Last_var, (char *)lpt_yytext); */
  return(MINIMISE);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
{
  /* strcpy(Last_var, (char *)lpt_yytext); */
  return(MAXIMISE);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
{
  /* strcpy(Last_var, (char *)lpt_yytext); */
  return(SUBJECTTO);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
{
  /* strcpy(Last_var, (char *)lpt_yytext); */
  return(BOUNDS);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
{
  /* strcpy(Last_var, (char *)lpt_yytext); */
  return(END);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
{
  f = atof((char *)lpt_yytext);
  return(INTCONS);
} /* f contains the last float */
	YY_BREAK
case 12:
YY_RULE_SETUP
{
  f = atof((char *)lpt_yytext);
  return(CONS);
} /* f contains the last float */
	YY_BREAK
case 13:
YY_RULE_SETUP
{
  char *ptr;

  f = DEF_INFINITE;
  Sign = 0;
  ptr = (char *)lpt_yytext;
  while (isspace(*ptr)) ptr++;
  if(*ptr == '-')
    Sign = 1;
  return(INF);
} /* f contains the last float */
	YY_BREAK
case 14:
YY_RULE_SETUP
{
  strcpy(Last_var0, Last_var);
  strcpy(Last_var, (char *)lpt_yytext);
  return(FR);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
{
  Sign = 0;
  for(x = 0; x < lpt_yyleng; x++)
    if(lpt_yytext[x] == '-' || lpt_yytext[x] == '+')
      Sign = (Sign == (lpt_yytext[x] == '+'));
  return (SIGN);
  /* Sign is TRUE if the sign-string
     represents a '-'. Otherwise Sign
     is FALSE */
}
	YY_BREAK
case 16:
YY_RULE_SETUP
{
  Within_gen_decl = Within_bin_decl = Within_sec_decl = Within_sos_decl = FALSE;
  if((toupper(*lpt_yytext) == 'G') || (toupper(*lpt_yytext) == 'I'))
    Within_gen_decl = TRUE;
  else
    Within_bin_decl = TRUE;
  return(SEC_INT);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
{
  Within_gen_decl = Within_bin_decl = Within_sec_decl = Within_sos_decl = FALSE;
  Within_sec_decl = TRUE;
  return(SEC_SEC);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
{
  Within_gen_decl = Within_bin_decl = Within_sec_decl = Within_sos_decl = FALSE;
  Within_sos_decl = TRUE;
  return(SEC_SOS);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
{
  strcpy(Last_var, (char *)lpt_yytext);
  return(SOSTYPE);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
{
  strcpy(Last_var, (char *)lpt_yytext);
  Last_var[strlen(Last_var) - 1] = 0;
  return(VARIABLECOLON);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
{
  strcpy(Last_var, (char *)lpt_yytext);
  return(VAR);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
{
  return(RE_OPLE);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
{
  return(RE_OPGE);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
{
  report(NULL, CRITICAL, "LEX ERROR : %s lineno %d\n", lpt_yytext, lpt_yylineno);
  return(UNDEFINED);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
ECHO;
	YY_BREAK
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(LINECOMMENT):
				lpt_yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int lpt_yy_amount_of_matched_text = (int) (lpt_yy_cp - lpt_yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*lpt_yy_cp = lpt_yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( lpt_yy_current_buffer->lpt_yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed lpt_yyin at a new source and called
			 * lpt_yylex().  If so, then we have to assure
			 * consistency between lpt_yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			lpt_yy_n_chars = lpt_yy_current_buffer->lpt_yy_n_chars;
			lpt_yy_current_buffer->lpt_yy_input_file = lpt_yyin;
			lpt_yy_current_buffer->lpt_yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for lpt_yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since lpt_yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( lpt_yy_c_buf_p <= &lpt_yy_current_buffer->lpt_yy_ch_buf[lpt_yy_n_chars] )
			{ /* This was really a NUL. */
			lpt_yy_state_type lpt_yy_next_state;

			lpt_yy_c_buf_p = lpt_yytext_ptr + lpt_yy_amount_of_matched_text;

			lpt_yy_current_state = lpt_yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * lpt_yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			lpt_yy_next_state = lpt_yy_try_NUL_trans( lpt_yy_current_state );

			lpt_yy_bp = lpt_yytext_ptr + YY_MORE_ADJ;

			if ( lpt_yy_next_state )
				{
				/* Consume the NUL. */
				lpt_yy_cp = ++lpt_yy_c_buf_p;
				lpt_yy_current_state = lpt_yy_next_state;
				goto lpt_yy_match;
				}

			else
				{
				lpt_yy_cp = lpt_yy_c_buf_p;
				goto lpt_yy_find_action;
				}
			}

		else switch ( lpt_yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				lpt_yy_did_buffer_switch_on_eof = 0;

				if ( lpt_yywrap() )
					{
					/* Note: because we've taken care in
					 * lpt_yy_get_next_buffer() to have set up
					 * lpt_yytext, we can now set up
					 * lpt_yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					lpt_yy_c_buf_p = lpt_yytext_ptr + YY_MORE_ADJ;

					lpt_yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! lpt_yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				lpt_yy_c_buf_p =
					lpt_yytext_ptr + lpt_yy_amount_of_matched_text;

				lpt_yy_current_state = lpt_yy_get_previous_state();

				lpt_yy_cp = lpt_yy_c_buf_p;
				lpt_yy_bp = lpt_yytext_ptr + YY_MORE_ADJ;
				goto lpt_yy_match;

			case EOB_ACT_LAST_MATCH:
				lpt_yy_c_buf_p =
				&lpt_yy_current_buffer->lpt_yy_ch_buf[lpt_yy_n_chars];

				lpt_yy_current_state = lpt_yy_get_previous_state();

				lpt_yy_cp = lpt_yy_c_buf_p;
				lpt_yy_bp = lpt_yytext_ptr + YY_MORE_ADJ;
				goto lpt_yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of lpt_yylex */


/* lpt_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int lpt_yy_get_next_buffer()
	{
	register char *dest = lpt_yy_current_buffer->lpt_yy_ch_buf;
	register char *source = lpt_yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( lpt_yy_c_buf_p > &lpt_yy_current_buffer->lpt_yy_ch_buf[lpt_yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( lpt_yy_current_buffer->lpt_yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( lpt_yy_c_buf_p - lpt_yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (lpt_yy_c_buf_p - lpt_yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( lpt_yy_current_buffer->lpt_yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		lpt_yy_current_buffer->lpt_yy_n_chars = lpt_yy_n_chars = 0;

	else
		{
		int num_to_read =
			lpt_yy_current_buffer->lpt_yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = lpt_yy_current_buffer;

			int lpt_yy_c_buf_p_offset =
				(int) (lpt_yy_c_buf_p - b->lpt_yy_ch_buf);

			if ( b->lpt_yy_is_our_buffer )
				{
				int new_size = b->lpt_yy_buf_size * 2;

				if ( new_size <= 0 )
					b->lpt_yy_buf_size += b->lpt_yy_buf_size / 8;
				else
					b->lpt_yy_buf_size *= 2;

				b->lpt_yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					lpt_yy_flex_realloc( (void *) b->lpt_yy_ch_buf,
							 b->lpt_yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->lpt_yy_ch_buf = 0;

			if ( ! b->lpt_yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			lpt_yy_c_buf_p = &b->lpt_yy_ch_buf[lpt_yy_c_buf_p_offset];

			num_to_read = lpt_yy_current_buffer->lpt_yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&lpt_yy_current_buffer->lpt_yy_ch_buf[number_to_move]),
			lpt_yy_n_chars, num_to_read );

		lpt_yy_current_buffer->lpt_yy_n_chars = lpt_yy_n_chars;
		}

	if ( lpt_yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			lpt_yyrestart( lpt_yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			lpt_yy_current_buffer->lpt_yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	lpt_yy_n_chars += number_to_move;
	lpt_yy_current_buffer->lpt_yy_ch_buf[lpt_yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	lpt_yy_current_buffer->lpt_yy_ch_buf[lpt_yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	lpt_yytext_ptr = &lpt_yy_current_buffer->lpt_yy_ch_buf[0];

	return ret_val;
	}


/* lpt_yy_get_previous_state - get the state just before the EOB char was reached */

static lpt_yy_state_type lpt_yy_get_previous_state()
	{
	register lpt_yy_state_type lpt_yy_current_state;
	register char *lpt_yy_cp;

	lpt_yy_current_state = lpt_yy_start;
	lpt_yy_current_state += YY_AT_BOL();
	lpt_yy_state_ptr = lpt_yy_state_buf;
	*lpt_yy_state_ptr++ = lpt_yy_current_state;

	for ( lpt_yy_cp = lpt_yytext_ptr + YY_MORE_ADJ; lpt_yy_cp < lpt_yy_c_buf_p; ++lpt_yy_cp )
		{
		register YY_CHAR lpt_yy_c = (*lpt_yy_cp ? lpt_yy_ec[YY_SC_TO_UI(*lpt_yy_cp)] : 1);
		while ( lpt_yy_chk[lpt_yy_base[lpt_yy_current_state] + lpt_yy_c] != lpt_yy_current_state )
			{
			lpt_yy_current_state = (int) lpt_yy_def[lpt_yy_current_state];
			if ( lpt_yy_current_state >= 138 )
				lpt_yy_c = lpt_yy_meta[(unsigned int) lpt_yy_c];
			}
		lpt_yy_current_state = lpt_yy_nxt[lpt_yy_base[lpt_yy_current_state] + (unsigned int) lpt_yy_c];
		*lpt_yy_state_ptr++ = lpt_yy_current_state;
		}

	return lpt_yy_current_state;
	}


/* lpt_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = lpt_yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static lpt_yy_state_type lpt_yy_try_NUL_trans( lpt_yy_state_type lpt_yy_current_state )
#else
static lpt_yy_state_type lpt_yy_try_NUL_trans( lpt_yy_current_state )
lpt_yy_state_type lpt_yy_current_state;
#endif
	{
	register int lpt_yy_is_jam;

	register YY_CHAR lpt_yy_c = 1;
	while ( lpt_yy_chk[lpt_yy_base[lpt_yy_current_state] + lpt_yy_c] != lpt_yy_current_state )
		{
		lpt_yy_current_state = (int) lpt_yy_def[lpt_yy_current_state];
		if ( lpt_yy_current_state >= 138 )
			lpt_yy_c = lpt_yy_meta[(unsigned int) lpt_yy_c];
		}
	lpt_yy_current_state = lpt_yy_nxt[lpt_yy_base[lpt_yy_current_state] + (unsigned int) lpt_yy_c];
	lpt_yy_is_jam = (lpt_yy_current_state == 137);
	if ( ! lpt_yy_is_jam )
		*lpt_yy_state_ptr++ = lpt_yy_current_state;

	return lpt_yy_is_jam ? 0 : lpt_yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void lpt_yyunput( int c, register char *lpt_yy_bp )
#else
static void lpt_yyunput( c, lpt_yy_bp )
int c;
register char *lpt_yy_bp;
#endif
	{
	register char *lpt_yy_cp = lpt_yy_c_buf_p;

	/* undo effects of setting up lpt_yytext */
	*lpt_yy_cp = lpt_yy_hold_char;

	if ( lpt_yy_cp < lpt_yy_current_buffer->lpt_yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = lpt_yy_n_chars + 2;
		register char *dest = &lpt_yy_current_buffer->lpt_yy_ch_buf[
					lpt_yy_current_buffer->lpt_yy_buf_size + 2];
		register char *source =
				&lpt_yy_current_buffer->lpt_yy_ch_buf[number_to_move];

		while ( source > lpt_yy_current_buffer->lpt_yy_ch_buf )
			*--dest = *--source;

		lpt_yy_cp += (int) (dest - source);
		lpt_yy_bp += (int) (dest - source);
		lpt_yy_current_buffer->lpt_yy_n_chars =
			lpt_yy_n_chars = lpt_yy_current_buffer->lpt_yy_buf_size;

		if ( lpt_yy_cp < lpt_yy_current_buffer->lpt_yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--lpt_yy_cp = (char) c;

	if ( c == '\n' )
		--lpt_yylineno;

	lpt_yytext_ptr = lpt_yy_bp;
	lpt_yy_hold_char = *lpt_yy_cp;
	lpt_yy_c_buf_p = lpt_yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int lpt_yyinput()
#else
static int input()
#endif
	{
	int c;

	*lpt_yy_c_buf_p = lpt_yy_hold_char;

	if ( *lpt_yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* lpt_yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( lpt_yy_c_buf_p < &lpt_yy_current_buffer->lpt_yy_ch_buf[lpt_yy_n_chars] )
			/* This was really a NUL. */
			*lpt_yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = lpt_yy_c_buf_p - lpt_yytext_ptr;
			++lpt_yy_c_buf_p;

			switch ( lpt_yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because lpt_yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					lpt_yyrestart( lpt_yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( lpt_yywrap() )
						return EOF;

					if ( ! lpt_yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return lpt_yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					lpt_yy_c_buf_p = lpt_yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) lpt_yy_c_buf_p;	/* cast for 8-bit char's */
	*lpt_yy_c_buf_p = '\0';	/* preserve lpt_yytext */
	lpt_yy_hold_char = *++lpt_yy_c_buf_p;

	lpt_yy_current_buffer->lpt_yy_at_bol = (c == '\n');
	if ( lpt_yy_current_buffer->lpt_yy_at_bol )
		++lpt_yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void lpt_yyrestart( FILE *input_file )
#else
void lpt_yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! lpt_yy_current_buffer )
		lpt_yy_current_buffer = lpt_yy_create_buffer( lpt_yyin, YY_BUF_SIZE );

	lpt_yy_init_buffer( lpt_yy_current_buffer, input_file );
	lpt_yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void lpt_yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void lpt_yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( lpt_yy_current_buffer == new_buffer )
		return;

	if ( lpt_yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*lpt_yy_c_buf_p = lpt_yy_hold_char;
		lpt_yy_current_buffer->lpt_yy_buf_pos = lpt_yy_c_buf_p;
		lpt_yy_current_buffer->lpt_yy_n_chars = lpt_yy_n_chars;
		}

	lpt_yy_current_buffer = new_buffer;
	lpt_yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (lpt_yywrap()) processing, but the only time this flag
	 * is looked at is after lpt_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	lpt_yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void lpt_yy_load_buffer_state( void )
#else
void lpt_yy_load_buffer_state()
#endif
	{
	lpt_yy_n_chars = lpt_yy_current_buffer->lpt_yy_n_chars;
	lpt_yytext_ptr = lpt_yy_c_buf_p = lpt_yy_current_buffer->lpt_yy_buf_pos;
	lpt_yyin = lpt_yy_current_buffer->lpt_yy_input_file;
	lpt_yy_hold_char = *lpt_yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE lpt_yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE lpt_yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) lpt_yy_flex_alloc( sizeof( struct lpt_yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in lpt_yy_create_buffer()" );

	b->lpt_yy_buf_size = size;

	/* lpt_yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->lpt_yy_ch_buf = (char *) lpt_yy_flex_alloc( b->lpt_yy_buf_size + 2 );
	if ( ! b->lpt_yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in lpt_yy_create_buffer()" );

	b->lpt_yy_is_our_buffer = 1;

	lpt_yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void lpt_yy_delete_buffer( YY_BUFFER_STATE b )
#else
void lpt_yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == lpt_yy_current_buffer )
		lpt_yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->lpt_yy_is_our_buffer )
		lpt_yy_flex_free( (void *) b->lpt_yy_ch_buf );

	lpt_yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void lpt_yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void lpt_yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	lpt_yy_flush_buffer( b );

	b->lpt_yy_input_file = file;
	b->lpt_yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->lpt_yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->lpt_yy_is_interactive = 0;
#else
	b->lpt_yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void lpt_yy_flush_buffer( YY_BUFFER_STATE b )
#else
void lpt_yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->lpt_yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->lpt_yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->lpt_yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->lpt_yy_buf_pos = &b->lpt_yy_ch_buf[0];

	b->lpt_yy_at_bol = 1;
	b->lpt_yy_buffer_status = YY_BUFFER_NEW;

	if ( b == lpt_yy_current_buffer )
		lpt_yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE lpt_yy_scan_buffer( char *base, lpt_yy_size_t size )
#else
YY_BUFFER_STATE lpt_yy_scan_buffer( base, size )
char *base;
lpt_yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) lpt_yy_flex_alloc( sizeof( struct lpt_yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in lpt_yy_scan_buffer()" );

	b->lpt_yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->lpt_yy_buf_pos = b->lpt_yy_ch_buf = base;
	b->lpt_yy_is_our_buffer = 0;
	b->lpt_yy_input_file = 0;
	b->lpt_yy_n_chars = b->lpt_yy_buf_size;
	b->lpt_yy_is_interactive = 0;
	b->lpt_yy_at_bol = 1;
	b->lpt_yy_fill_buffer = 0;
	b->lpt_yy_buffer_status = YY_BUFFER_NEW;

	lpt_yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE lpt_yy_scan_string( lpt_yyconst char *lpt_yy_str )
#else
YY_BUFFER_STATE lpt_yy_scan_string( lpt_yy_str )
lpt_yyconst char *lpt_yy_str;
#endif
	{
	int len;
	for ( len = 0; lpt_yy_str[len]; ++len )
		;

	return lpt_yy_scan_bytes( lpt_yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE lpt_yy_scan_bytes( lpt_yyconst char *bytes, int len )
#else
YY_BUFFER_STATE lpt_yy_scan_bytes( bytes, len )
lpt_yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	lpt_yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) lpt_yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in lpt_yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = lpt_yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in lpt_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->lpt_yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void lpt_yy_push_state( int new_state )
#else
static void lpt_yy_push_state( new_state )
int new_state;
#endif
	{
	if ( lpt_yy_start_stack_ptr >= lpt_yy_start_stack_depth )
		{
		lpt_yy_size_t new_size;

		lpt_yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = lpt_yy_start_stack_depth * sizeof( int );

		if ( ! lpt_yy_start_stack )
			lpt_yy_start_stack = (int *) lpt_yy_flex_alloc( new_size );

		else
			lpt_yy_start_stack = (int *) lpt_yy_flex_realloc(
					(void *) lpt_yy_start_stack, new_size );

		if ( ! lpt_yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	lpt_yy_start_stack[lpt_yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void lpt_yy_pop_state()
	{
	if ( --lpt_yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(lpt_yy_start_stack[lpt_yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int lpt_yy_top_state()
	{
	return lpt_yy_start_stack[lpt_yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void lpt_yy_fatal_error( lpt_yyconst char msg[] )
#else
static void lpt_yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine lpt_yyless() so it works in section 3 code. */

#undef lpt_yyless
#define lpt_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up lpt_yytext. */ \
		lpt_yytext[lpt_yyleng] = lpt_yy_hold_char; \
		lpt_yy_c_buf_p = lpt_yytext + n; \
		lpt_yy_hold_char = *lpt_yy_c_buf_p; \
		*lpt_yy_c_buf_p = '\0'; \
		lpt_yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef lpt_yytext_ptr
#ifdef YY_USE_PROTOS
static void lpt_yy_flex_strncpy( char *s1, lpt_yyconst char *s2, int n )
#else
static void lpt_yy_flex_strncpy( s1, s2, n )
char *s1;
lpt_yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int lpt_yy_flex_strlen( lpt_yyconst char *s )
#else
static int lpt_yy_flex_strlen( s )
lpt_yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *lpt_yy_flex_alloc( lpt_yy_size_t size )
#else
static void *lpt_yy_flex_alloc( size )
lpt_yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *lpt_yy_flex_realloc( void *ptr, lpt_yy_size_t size )
#else
static void *lpt_yy_flex_realloc( ptr, size )
void *ptr;
lpt_yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void lpt_yy_flex_free( void *ptr )
#else
static void lpt_yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	lpt_yylex();
	return 0;
	}
#endif

