/*
 * Graphic module CORBA interface
 *
 * Author:
 *   Miguel de Icaza (miguel@gnu.org)
 *
 * (C) 1999 International GNOME Support (http://www.gnome-support.com)
 */

#include <bonobo.idl>
#include "Gnumeric-value.idl"


module GNOME {

	module Graph {
		
		enum ScaleType {
			SCALE_TYPE_LINEAR,
			SCALE_TYPE_LOGARITMIC,
			SCALE_TYPE_PERCENT
		};

		interface AxisScale {
			/*
			 * Whether the Axis is hidden
			 */
			attribute boolean hidden;

			ScaleType type ();

			/*
			 * The logaritmic base
			 */
			attribute short log_base;
		};

		enum AngleUnit {
			ANGLE_DEGREES,
			ANGLE_RADIANS,
			ANGLE_GRADS
		};

		interface Plot {
			// 
			// Units of measure used for chart angles 
			//
			attribute AngleUnit angle_unit;
			
			//
			// Direction in which pie charts are drawn
			//
			attribute boolean clockwise;

			//
			// Whether the slices of a pie are sorted
			//
			attribute boolean sorted;

			//
			// 
			//
			// Backdrop backdrop ();

			//
			// Starting angle for drawing pie charts. 
			//
			attribute short starting_angle;
		};

		enum ChartType {
			//
			// Columns or bars where groups of ith-elements
			// are plotted next to each other.
			CHART_TYPE_CLUSTERED,

			//
			// ith-values of each series are stacked
			// on top of each other.
			//
			CHART_TYPE_STACKED,

			//
			// Values fill entire plot
			//
			CHART_TYPE_STACKED_FULL,

			//
			// Extra axis displays i-th
			//
			CHART_TYPE_3D,

			//
			// Pie
			//
			CHART_TYPE_PIE,

			//
			// Scatter
			//
			CHART_TYPE_SCATTER,

			//
			// Surface
			//
			CHART_TYPE_SURFACE_2D,
			CHART_TYPE_SURFACE_3D,

			//
			// Bubbles
			//
			CHART_TYPE_BUBBLES,

			//
			// Stock
			//
			CHART_TYPE_STOCK_HIGH_LOW_CLOSE,
			CHART_TYPE_STOCK_OPEN_HIGH_LOW_CLOSE,
			CHART_TYPE_STOCK_VOL_HIGH_LOW_CLOSE,
			CHART_TYPE_STOCK_VOL_OPEN_HIGH_LOW_CLOSE

		};

		enum PlotMode {
			PLOT_COLBAR,		// Columns or bars.
			PLOT_LINES,		// Lines 
			PLOT_AREA		// Areas
		};

		enum ColBarMode {
			COLBAR_FLAT,
			COLBAR_CUBE,
			COLBAR_PIRAMID,
			COLBAR_CONE,
			COLBAR_CYLINDER
		};

		enum DirMode {
			DIR_BAR,
			DIR_COL
		};

		enum LineMode {
			LINE_PLAIN,
			LINE_MARKERS
		};

		enum PieMode {
			PIE_SIMPLE,
			PIE_EXPLODED
		};

		enum PieDimension {
			PIE_2D,
			PIE_3D
		};

		enum ScatterPoints {
			SCATTER_NONE,
			SCATTER_POINTS
		};

		enum ScatterConn {
			SCATTER_CONN_NONE,
			SCATTER_CONN_SMOOTH,
			SCATTER_CONN_LINES
		};

		enum SurfaceMode {
			SURFACE_WIREFRAME,
			SURFACE_COLORED
		};

		interface Chart : GNOME::Unknown {
			attribute ChartType     chart_type;
			attribute PlotMode      plot_mode;
			attribute ColBarMode    col_bar_mode;
			attribute DirMode       direction;
			attribute LineMode      line_mode;
			attribute PieMode       pie_mode;
			attribute PieDimension  pie_dim;
			attribute ScatterPoints scatter_mode;
			attribute ScatterConn   scatter_conn;
			attribute SurfaceMode   surface_mode;
			
			//
			// Methods for avoiding un-needed repaints.
			//
			void freeze ();
			void thaw ();

			void reset_series ();
			void add_series (in string label, in Vector vector);
		};
	};
};
