/* vim: set sw=8 ts=8: -*- Mode: C; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/**
 * excel-xml-read.h : Import MS Excel (tm) XML generated by version XP
 *
 * Copyright (C) 2003-2005 Jody Goldberg (jody@gnome.org)
 **/
#ifndef EXCEL_XML_READ_H
#define EXCEL_XML_READ_H

#endif /* EXCEL_XML_READ_H */
