.TH GNUMERIC 1 "January 1, 2002" gnumeric "GNOME"
.SH NAME
gnumeric \- a GNOME spreadsheet application.

.SH SYNOPSIS
\fBgnumeric\fR [\fIOPTIONS\fR] [\fIfiles\fR \fI...\fR ]

.SH DESCRIPTION
\fBgnumeric\fR is a powerful spreadsheet program created by the GNOME
project. \fBgnumeric\fR intends to compete with commercial spreadsheets
by becoming fully compatible with Microsoft Excel and through the support 
of most popular spreadsheet file formats such as Excel, Lotus 1-2-3, Applix, 
Sylk, XBase and Oleo formats.

\fBgnumeric\fR supports advanced calculations using statistical, financial 
and database access functions. Plotting data is supported through an 
interface to the \fBGuppi\fR plotting program. A plugin system extends 
\fBgnumeric\fR to enable the use the Python, Guile, or Perl programing 
languages and to enable the export of data to the LaTeX \\longtable format.

The program can be started from the command line as \fBgnumeric\fR or from one
of the menus provided by underlying platform. When started on the command
line, \fBgnumeric\fR may be followed by the options listed below and possibly
the names of \fBgnumeric\fR compressed XML format files which will then be 
opened immediately.

.SH OPTIONS
This program follows the usual GNU command line syntax, with long options
starting with two dashes (`--'). 
.SS "Oaf options"
.TP
\fB\-\-oaf-od-ior=\fR\fIIOR\fR
Object directory to use when registering servers
.TP
\fB\-\-oaf-ior-fd=\fR\fIFD\fR
File descriptor to print \fIIOR\fR on
.TP
\fB\-\-oaf-activate-iid=\fR\fIIID\fR
\fIIID\fR to activate
.TP
.B \-\-oaf-private
Prevent registering of server with OAF

.SS "GNOME options"
.TP
.B \-\-disable-sound
Disable sound server usage
.TP
.B \-\-enable-sound
Enable sound server usage
.TP
\fB\-\-espeaker=\fR\fIHOSTNAME:PORT\fR
Host:port on which the sound server to use is running

.SS "Help options"
.B \-?, \-\-help
Show help message
.TP
.B \-\-usage
Display brief usage message

.SS "GTK options"
.TP
\fB\-\-gdk-debug=\fR\fIFLAGS\fR
Gdk debugging flags to set
.TP
\fB\-\-gdk-no-debug=\fR\fIFLAGS\fR
Gdk debugging flags to unset
.TP
\fB\-\-display=\fR\fIDISPLAY\fR
X display to use
.TP
.B \-\-sync
Make X calls synchronous
.TP
.B \-\-no-xshm
Don't use X shared memory extension
.TP
\fB\-\-name=\fR\fINAME\fR
Program name as used by the window manager
.TP
\fB\-\-class=\fR\fICLASS\fR
Program class as used by the window manager
.TP
\fB\-\-gxid_host=\fR\fIHOST\fR
.TP
\fB\-\-gxid_port=\fR\fIPORT\fR
.TP
\fB\-\-xim-preedit=\fR\fISTYLE\fR
.TP
\fB\-\-xim-status=\fR\fISTYLE\fR
.TP
\fB\-\-gtk-debug=\fR\fIFLAGS\fR
Gtk+ debugging flags to set
.TP
\fB\-\-gtk-no-debug=\fR\fIFLAGS\fR
Gtk+ debugging flags to unset
.TP
\fB\-\-g-fatal-warnings\fR
Make all warnings fatal
.TP
\fB\-\-gtk-module=\fR\fIMODULE\fR
Load an additional Gtk module

.SS "GNOME GUI options"
.TP
.B \-\-disable-crash-dialog

.SS "Session management options"
.TP
\fB\-\-sm-client-id=\fR\fIID\fR
Specify session management ID
.TP
\fB\-\-sm-config-prefix=\fR\fIPREFIX\fR
Specify prefix of saved configuration
.TP
.B \-\-sm-disable
Disable connection to session manager

.SS "X options"
.TP
\fB\-geom, \-\-geometry=\fIgeometry\fR
Set the size and position of the first window.

.SS "gnumeric options"
.TP
.B \-v, \-\-version
Display \fBgnumeric\fR's version
.TP
\fB\-L, \-\-lib-dir=\fR\fISTRING\fR
Set the root library directory
.TP
\fB\-D, \-\-data-dir=\fR\fISTRING\fR
Adjust the root data directory
.TP
\fB\-\-dump-func-defs=\fR\fIFILE\fR
Dumps the function definitions
.TP
\fB\-\-debug=\fR\fILEVEL\fR
Enables some debugging functions
.TP
.BI \-\-debug_deps= LEVEL
Enables some dependency related debugging functions
.TP
.BI \-\-debug_print= LEVEL
Enables some print debugging behavior
.TP
.B \-\-quit
Exit immediately after loading the selected books (useful for testing).
.TP
.B \-\-debug_ole
Enables extra consistency checking while reading ole files

.SH VERSION
1.0

.SH BUGS
For the list of known \fBgnumeric\fR bugs, or to report new ones please 
visit \fIhttp://bugzilla.gnome.org\fR.

.SH "SEE ALSO"
.TP
.B The gnumeric manual
Available through the \fBHelp\fR menu or on the world wide web at 
\fIhttp://www.gnome.org/projects/gnumeric/doc/index.html\fR
.TP
.B The gnumeric homepage
.I http://www.gnome.org/projects/gnumeric/
.TP
.B The GNOME project
.I http://www.gnome.org

.SH LICENSE

\fBgnumeric\fR is licensed under the terms of the General Public License
version 2. For information on this license look at the source code that came
with the software or see the GNU project page at http://www.gnu.org.

.SH COPYRIGHT

The copyright on the \fBgnumeric\fR software and source code is held by the
individual authors as is documented in the source code.


.SH AUTHORS
.SS "gnumeric"
Jody Goldberg <jgoldberg@gnome.org>
.br
Miguel de Icaza <miguel@gnome.org>
.SS "This manual page"
Jan Schaumann <jschauma@netmeister.org>
.br
Adrian Custer <acuster@nature.berkeley.edu>
