/etc/gconf/schemas/*.schemas
/usr/bin/gnumeric*
/usr/bin/ssconvert*
/usr/bin/ssgrep*
/usr/bin/ssindex*
# /usr/lib/gnumeric/*/plugins/*/*.glade
/usr/lib/gnumeric/*/plugins/*/*.la
/usr/lib/gnumeric/*/plugins/*/*.so
/usr/lib/gnumeric/*/plugins/*/*.xml
/usr/lib/libspreadsheet-*.so*
/usr/lib/libspreadsheet.so
/usr/lib/gnumeric/*/include/gnumeric-features.h
/usr/share/gnumeric/*/GNOME_Gnumeric-gtk.xml
# /usr/share/gnumeric/*/Gnumeric-embed.xml
/usr/share/man/man*/*
