/usr/share/applications/gnumeric.desktop
/usr/share/gnumeric/*.md5sum
/usr/share/gnumeric/*/autoformat-templates/*/*.xml
/usr/share/gnumeric/*/autoformat-templates/*/.category
/usr/share/gnumeric/*/ui/*.ui
# /usr/share/gnumeric/*/gnome*/ui/*.xml
# /usr/share/gnumeric/*/idl/*.idl
/usr/share/gnumeric/*/templates/*.gnumeric
/usr/share/locale/*/LC_MESSAGES/*.mo
# /usr/share/mime-info/gnumeric.*
/usr/share/pixmaps/*
/usr/share/icons/
/usr/share/glib-*/schemas/org.gnome.gnumeric.*.xml
