/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Gnumeric : Structured text file import");
gchar *s = N_("Importing a structured text file");
gchar *s = N_("This dialog will help you import your structured text file.\n"
              "\n"
              "You can hit cancel at any time to quit");
gchar *s = N_("Data type and number of lines");
gchar *s = N_("Choose the data type that most closely matches the structure of the original file");
gchar *s = N_("Original data type");
gchar *s = N_("_Separated");
gchar *s = N_("_Fixed width");
gchar *s = N_("Start _importing at line: ");
gchar *s = N_("Number of lines to import");
gchar *s = N_("Example output from file");
gchar *s = N_("Separation customization");
gchar *s = N_("Select what separators appear in the text. In the example you can see the effect of your selections.");
gchar *s = N_("Separators");
gchar *s = N_("_Tab");
gchar *s = N_("C_omma");
gchar *s = N_("S_pace");
gchar *s = N_("C_ustom");
gchar *s = N_("_Colon");
gchar *s = N_("Misc");
gchar *s = N_("S_ee two separators as one");
gchar *s = N_("Te_xt indicator : ");
gchar *s = N_("\"\n"
              "'\n"
              "`\n"
              "");
gchar *s = N_("\"");
gchar *s = N_("Example");
gchar *s = N_("Fixed width customization");
gchar *s = N_("Select the column widths (ends)");
gchar *s = N_("Columns");
gchar *s = N_("Column");
gchar *s = N_("End");
gchar *s = N_("Co_lumn end : ");
gchar *s = N_("_Add");
gchar *s = N_("_Remove");
gchar *s = N_("Example");
gchar *s = N_("Column formatting");
gchar *s = N_("Set the format per column, you can click on a column in the list to change the format");
gchar *s = N_("Per column formatting");
gchar *s = N_("Column");
gchar *s = N_("Format");
gchar *s = N_("For_mat :");
gchar *s = N_("label8");
gchar *s = N_("Example");
gchar *s = N_("Finish");
gchar *s = N_("You have successfully imported your structured text file\n"
              "\n"
              "Please press finish");
