/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("dialog3");
gchar *s = N_("Cancel");
gchar *s = N_("<< _Previous");
gchar *s = N_("_Next step >>");
gchar *s = N_("_Finish");
gchar *s = N_("_Graphic type:");
gchar *s = N_("Graphic subtype:");
gchar *s = N_("label15");
gchar *s = N_("label16");
gchar *s = N_("Plot description");
gchar *s = N_("_Show sample");
gchar *s = N_("Standard Types");
gchar *s = N_("Custom types");
gchar *s = N_("Step1");
gchar *s = N_("_Data Range:");
gchar *s = N_("_Rows");
gchar *s = N_("_Columns");
gchar *s = N_("Series in:");
gchar *s = N_("Data ranges");
gchar *s = N_("Serie:");
gchar *s = N_("label27");
gchar *s = N_("_Add");
gchar *s = N_("_Remove");
gchar *s = N_("_Name:");
gchar *s = N_("_Value:");
gchar *s = N_("Labels for the _X axis:");
gchar *s = N_("Series");
gchar *s = N_("Step2");
gchar *s = N_("_Plot title:");
gchar *s = N_("_X axis label:");
gchar *s = N_("_Y axis label:");
gchar *s = N_("_Second X axis values:");
gchar *s = N_("S_econd Y axis values:");
gchar *s = N_("Titles");
gchar *s = N_("Principal Axis");
gchar *s = N_("_X axis");
gchar *s = N_("_Automatic");
gchar *s = N_("_Category");
gchar *s = N_("_Scale");
gchar *s = N_("_Y axis");
gchar *s = N_("_Z axis");
gchar *s = N_("Axis");
gchar *s = N_(" X axis ");
gchar *s = N_("_Main line divisions");
gchar *s = N_("_Secondary line divisions");
gchar *s = N_(" Y axis ");
gchar *s = N_("M_ain line divisions");
gchar *s = N_("S_econdary line divisions");
gchar *s = N_("Division lines");
gchar *s = N_("_Show legend");
gchar *s = N_(" Location ");
gchar *s = N_("_Down");
gchar *s = N_("_Corner");
gchar *s = N_("_Up");
gchar *s = N_("_Right");
gchar *s = N_("_Left");
gchar *s = N_("Legends");
gchar *s = N_("Step3");
