CC=gcc
CFLAGS=-I/usr/include/python1.5 `gnome-config --cflags gnomeui`
LIBS=-L/usr/lib/python1.5/config -lpython1.5 -lc

all: python.so

.c.o:
	$(CC) $(CFLAGS) -c $<

python.so: python.o
	gcc -shared -o python.so python.o $(LIBS)

clean:
	rm -f *.o *.so *~
