#!/bin/sh
dir=`basename "$1" .xlsx`
rm -rf "$dir"
mkdir "$dir"
cd "$dir"
unzip ../"$1"
xmls=`find . -name \*.xml`
rels=`find . -name \*.rels`
for f in $xmls $rels ; do
    xmllint --format "$f" > dumper.xml
    mv dumper.xml "$f"
done
