#ifndef __GNUMERIC_IDL__
#define __GNUMERIC_IDL__

/*
 * If you are looking for a good example of Bonobo use, this is not it.
 * please see bonobo/samples/ for a better starting point.
 */

#include <Bonobo.idl>

module GNOME {
	module Gnumeric {
		interface Sheet {
			attribute string name;
		};
		interface Workbook {
			attribute string name;
		};
		interface Application {
			Workbook new_workbook ();
			Workbook open_workbook (in string file);
		};
	};
};


#endif /* __GNUMERIC_IDL__ */
