/**
 * The interfaces Gnumeric uses to communicate with graphing components
 *
 * Author:
 *   Jody Goldberg <jgoldberg@home.com>
 */
#include <Bonobo.idl>

module GNOME {
	module Gnumeric {
		interface VectorNotify {
			oneway void headerChanged (in string header);
		};

		typedef sequence<double> SeqScalar;
		interface VectorScalarNotify : VectorNotify {
			oneway void valueChanged (in short start, in SeqScalar new_values);
		};
		interface VectorScalar : VectorScalarNotify {
			void value (out SeqScalar values);
		};

		typedef sequence<long> SeqDate;
		interface VectorDateNotify : VectorNotify {
			oneway void valueChanged (in short start, in SeqDate new_values);
		};
		interface VectorDate : VectorDateNotify {
			void value (out SeqDate values);
		};

		typedef sequence<string> SeqString;
		interface VectorStringNotify : VectorNotify {
			oneway void valueChanged (in short start, in SeqString new_values);
		};
		interface VectorString : VectorStringNotify {
			void value (out SeqString values);
		};

		module Graph {
			interface Manager_v1 : Bonobo::Unknown {
				Bonobo::Control getTypeSelectControl ();
				Bonobo::Control getLayoutControl ();

				VectorScalarNotify addVectorScalar (in VectorScalar v, in long id);
				VectorDateNotify   addVectorDate   (in VectorDate   v, in long id);
				VectorStringNotify addVectorString (in VectorString v, in long id);

				oneway void freeze (in boolean flag);
				oneway void clearVectors ();
			};
		};
	};
};
