/**
 * The interfaces Gnumeric uses to communicate with graphing components
 *
 * Author:
 *   Jody Goldberg <jgoldberg@home.com>
 */
#include <Bonobo.idl>

module GNOME {
    module Gnumeric {
	struct Pair {
	    short start;
	    short end;
	};
	/* This is a place holder */
	typedef sequence<Pair> SeqPair;
	interface VectorSelection {
	    oneway void selected (in SeqPair ranges);
	};
	module Scalar {
	    typedef sequence<double> Seq;
	    interface Vector : VectorSelection {
		oneway void changed (in short start, in Seq new_values);
		void value (out Seq values);
	    };
	};
	module Date {
	    typedef sequence<long> Seq;
	    interface Vector : VectorSelection {
		oneway void changed (in short start, in Seq new_values);
		void value (out Seq values);
	    };
	};
	module String {
	    typedef sequence<string> Seq;
	    interface Vector : VectorSelection {
		oneway void changed (in short start, in Seq new_values);
		void value (out Seq values);
	    };
	};

	module Graph {
	    interface Manager_v2 : Bonobo::Unknown {
		typedef long VectorID;
		typedef sequence<VectorID> VectorIDs;
		typedef sequence<octet>	Buffer;

		Scalar::Vector addScalarVector (in Scalar::Vector v, in VectorID id);
		Date::Vector   addDateVector   (in Date::Vector   v, in VectorID id);
		String::Vector addStringVector (in String::Vector v, in VectorID id);

		/**
		 * clearVectors :
		 *
		 * Remove all references to the existing set of vectors.
		 */
		oneway void clearVectors ();

		/**
		 * arrangeVectors :
		 *
		 * Take the set of vectors and their optional
		 * headers in the order specified by the
		 * supplied @data ids, and arrange them into a
		 * graph using the 'current' graph type.
		 */
		oneway void arrangeVectors (in VectorIDs data,
					    in VectorIDs optional_headers);

		Bonobo::Control getTypeSelectControl ();

		/**
		 * importSpecification :
		 *
		 * Take a possibly incomplete description of a
		 * graph using a subset of the dtd used for
		 * persistence and initialize the graphs state.
		 * The document refers to vectors by IDs that
		 * were assigned previously.
		 */
		oneway void importSpecification (in Buffer spec);
	    };
	};
    };
};
