#!/usr/bin/perl -w
#
# import-GLPK: Use this Perl script to import GLPK into Gnumeric.
#              Tested with glpk 4.2.
#
# GLPK is the GNU Linear Programming Kit. You can get the latest version
# from any GNU mirror ftp site in the glpk directory.
#
# The script performs the following modifications to the original source
# code:
#       - imports only the selected files from the original source code
#         distribution
#       - creates the necessary 'Makefile.am's
#       - uses gnm_float instead of double in all places
#	- uses sqrtgnum, ... instead of sqrt, ... in all places
#
#
# Author:
#         Jukka-Pekka Iivonen <jiivonen@hutcs.cs.hut.fi>
#


#
# Check the command line arguments.
#

my $glpk_path = $ARGV[0];
my $dest_path = $ARGV[1];

# Check paths.
if (!defined ($glpk_path) || !defined ($dest_path)) {
    print "Usage: import-GLPK <glpk-path> <destination-path>\n";
    print "Both paths should be directories.\n\n";
    exit;
}


#
# Create destination directory hierarchy
#

#system "rm -rf $dest_path";
mkdir $dest_path;
mkdir "$dest_path/doc";
mkdir "$dest_path/include";
mkdir "$dest_path/src";


#
# Select files that are copied as is, like documentation etc.
#

$x=0;

$files[$x++] = "AUTHORS";
$files[$x++] = "ChangeLog";
$files[$x++] = "NEWS";
$files[$x++] = "README";
$files[$x++] = "doc/bench.txt";
$files[$x++] = "doc/lang.latex";
$files[$x++] = "doc/refman.latex";
$files[$x++] = "@";

for ($i = 0; $files[$i] ne "@"; $i++) {
    system "cp $glpk_path/$files[$i] $dest_path/$files[$i]";
}


#
# Select source code files that are filtered to be Gnumeric friedly.
#

# Add these Gnumeric headers
my @gnumeric_inc =
    ("gnumeric-config.h",
     "gnumeric.h",
     "numbers.h",
     "@");

# Select these sources to be imported into Gnumeric
$x=0;

##$src[$x++] = "include/glpavl.h";
##$src[$x++] = "include/glpchol.h";
$src[$x++] = "include/glpdmp.h";
##$src[$x++] = "include/glphbsm.h";
$src[$x++] = "include/glpies.h";
$src[$x++] = "include/glpiet.h";
$src[$x++] = "include/glpinv.h";
$src[$x++] = "include/glpios.h";
##$src[$x++] = "include/glpipm.h";
$src[$x++] = "include/glpk.h";
$src[$x++] = "include/glplib.h";
$src[$x++] = "include/glplpp.h";
##$src[$x++] = "include/glplpt.h";
$src[$x++] = "include/glplpx.h";
$src[$x++] = "include/glpluf.h";
#$src[$x++] = "include/glpmat.h";
$src[$x++] = "include/glpmip.h";
##$src[$x++] = "include/glpmpl.h";
##$src[$x++] = "include/glpmps.h";
##$src[$x++] = "include/glpqmd.h";
$src[$x++] = "include/glpspm.h";
$src[$x++] = "include/glpspx.h";
$src[$x++] = "include/glpstr.h";
##$src[$x++] = "include/glptsp.h";



##$src[$x++] = "src/glpavl.c";
##$src[$x++] = "src/glpchol.c";
$src[$x++] = "src/glpdmp.c";      # glp_dmp_get_atomv, ...
##$src[$x++] = "src/glphbsm.c";
$src[$x++] = "src/glpies1.c";
$src[$x++] = "src/glpies2.c";
$src[$x++] = "src/glpies3.c";
##$src[$x++] = "src/glpiet.c";
$src[$x++] = "src/glpinv.c";      # inv_btran, ...
##$src[$x++] = "src/glpios1.c";
##$src[$x++] = "src/glpios2.c";
##$src[$x++] = "src/glpios3.c";
##$src[$x++] = "src/glpipm.c";
$src[$x++] = "src/glplib1a.c";
$src[$x++] = "src/glplib1b.c";
$src[$x++] = "src/glplib2.c";     # ucalloc, ...
$src[$x++] = "src/glplib3.c";     # get_atom
$src[$x++] = "src/glplib4.c";
$src[$x++] = "src/glplpp1.c";
$src[$x++] = "src/glplpp2.c";     # lpp_presolve
##$src[$x++] = "src/glplpt.c";
$src[$x++] = "src/glplpx1.c";     # lpx_set_row_bnds, lpx_create_prob,...
$src[$x++] = "src/glplpx2.c";     # lpx_get_mat_col, ...
$src[$x++] = "src/glplpx3.c";     # lpx_reset_parms
$src[$x++] = "src/glplpx4.c";     # lpx_scale_prob, lpx_unscale_prob
$src[$x++] = "src/glplpx5.c";
$src[$x++] = "src/glplpx6a.c";    # lpx_simplex
##$src[$x++] = "src/glplpx6b.c";
$src[$x++] = "src/glplpx6c.c";    # lpx_integer
##$src[$x++] = "src/glplpx6d.c";
$src[$x++] = "src/glplpx7.c";
##$src[$x++] = "src/glplpx8a.c";
##$src[$x++] = "src/glplpx8b.c";
##$src[$x++] = "src/glplpx8c.c";
##$src[$x++] = "src/glplpx8d.c";
$src[$x++] = "src/glpluf.c";      # luf_create
##$src[$x++] = "src/glpmat.c";
$src[$x++] = "src/glpmip1.c";     # mip_delete_tree
##$src[$x++] = "src/glpmpl1.c";
##$src[$x++] = "src/glpmpl2.c";
##$src[$x++] = "src/glpmpl3.c";
##$src[$x++] = "src/glpmpl4.c";
##$src[$x++] = "src/glpmps.c";
##$src[$x++] = "src/glpqmd.c";
$src[$x++] = "src/glpspm.c";      # spm_delete, ...
$src[$x++] = "src/glpspx1.c";     # spx_update, ...
$src[$x++] = "src/glpspx2.c";     # spx_reset_refsp, ...
$src[$x++] = "src/glpstr.c";
##$src[$x++] = "src/glptsp.c";

$src[$x++] = "@";


#
# Filter sources
#

for ($i = 0; $src[$i] ne "@"; $i++) {
    open IN, "$glpk_path/$src[$i]";
    open OUTFILE, ">$dest_path/$src[$i]";
    $flag = 0;

    print "$src[$i]\n";

    while (<IN>) {

	if (/(.*)/) {
	    # Filtering

	    $line = $1;
	    # Use gnm_float instead of double
	    while ($line =~s/double/gnm_float/) {}

	    # Use sqrtgnum instead of sqrt, etc.
	    $line =~ s/\b(sqrt|exp|log|pow|log1p|expm1|ceil|floor|sin|sinh|tan)(\s|$|\()/$1gnum$2/g;
	    $line =~ s/\bfabs\b/gnumabs/g;

	    # Use g_malloc instead of malloc
	    $line =~s/[^u]malloc\s*\(/g_malloc \(/g;

	    # Use g_free instead of free
	    $line =~s/[^u]free\s*\(/g_free \(/g;

	    # Constify a few routines.
	    if (/^void\s+(_insist|lib_set_fault_hook|fault|lib_set_print_hook|print)\b/) {
		$line =~s/\bchar\s+\*/const char */g;
	    }

	    print OUTFILE "$line\n";

	    # Add Gnumeric headers
	    if ($flag && $line=~/\#\s*define\s*_(\w+)_H/) {
		if ($1 eq $header_name) {
		    print OUTFILE "\n";
		    for ($t = 0; $gnumeric_inc[$t] ne "@"; $t++) {
			print OUTFILE "\#include \"$gnumeric_inc[$t]\"\n";
		    }
		    $flag = 0;
		    $header_name = "";
		}
	    } elsif ($line =~/\#\s*ifndef\s*_(\w+)_H/) {
		$flag = 1;
		$header_name = $1;
	    } else {
		$flag = 0;
		$header_name = "";
	    }
	}
    }

    close OUTFILE;
    close IN;
}

#
# Create 'Makefile.am's
#

# glpk/Makefile.am
open OUTFILE, ">$dest_path/Makefile.am";
print OUTFILE "SUBDIRS = source\n\n";
print OUTFILE "INCLUDES =\t\t\t\t\t\t\\\n";
print OUTFILE "\t-DGNOMELOCALEDIR=\\\"\"\$(datadir)/locale\"\\\"\t\\\n";
print OUTFILE "\t-I\$(top_srcdir)\t\t\t\t\t\\\n";
print OUTFILE "\t-I\$(top_srcdir)/src\t\t\t\t\\\n";
print OUTFILE "\t-I\$(top_srcdir)/src/tools\t\t\t\\\n";
print OUTFILE "\t-I\$(top_srcdir)/src/tools/solver\t\t\\\n";
print OUTFILE "\t-I\$(top_srcdir)/src/tools/solver/glpk/include\t\\\n";
print OUTFILE "\t\$(GNUMERIC_CFLAGS)\n\n";
print OUTFILE "noinst_LIBRARIES =\n\n";
close OUTFILE;

# glpk/source/Makefile.am
open OUTFILE, ">$dest_path/src/Makefile.am";
print OUTFILE "SUBDIRS = \n\n";
print OUTFILE "INCLUDES =\t\t\t\t\t\t\\\n";
print OUTFILE "\t-DGNOMELOCALEDIR=\\\"\"\$(datadir)/locale\"\\\"\t\\\n";
print OUTFILE "\t-I\$(top_srcdir)\t\t\t\t\t\\\n";
print OUTFILE "\t-I\$(top_srcdir)/src\t\t\t\t\\\n";
print OUTFILE "\t-I\$(top_srcdir)/src/tools\t\t\t\\\n";
print OUTFILE "\t-I\$(top_srcdir)/src/tools/solver\t\t\\\n";
print OUTFILE "\t-I\$(top_srcdir)/src/tools/solver/glpk/include\t\\\n";
print OUTFILE "\t\$(GNUMERIC_CFLAGS)\n\n";
print OUTFILE "noinst_LIBRARIES = libglpk.a\n\n";
print OUTFILE "libglpk_a_SOURCES =\t\t\t\t\t\\\n";
for ($i = 0; $src[$i] ne "@"; $i++) {
    $name = $src[$i];
    if ($name=~/include\//) {
	next;
    }
    $name =~s/src\///;
    print OUTFILE "\t$name\t\t\t\t";
    if ($src[$i + 1] eq "@") {
	print OUTFILE "\n";
    } else {
	print OUTFILE "\\\n";
    }
}
print OUTFILE "\t\n";
print OUTFILE "\t\n";
print OUTFILE "\t\n";
close OUTFILE;

rename "$dest_path/src","$dest_path/source";
