#! /usr/bin/perl -w

use strict;

my $realitstool = shift @ARGV;

my $tmp;
END { unlink $tmp if defined $tmp; }

if (@ARGV > 2 &&
    $ARGV[0] eq '-o' &&
    $ARGV[1] =~ /\.pot/) {
    my ($dasho, $potfile, $main) = @ARGV;

    $tmp = $main;
    $tmp =~ s/\.xml$/-tmp.xml/;

    my @cmd = ("xmllint", "--noent", "-o", $tmp, $main);
    print STDERR "# [WRAP] Running ", join(" ", @cmd), "\n";
    system(@cmd);
    exit 1 unless $? == 0;

    @cmd = ($realitstool, $dasho, $potfile, $tmp);
    print STDERR "# [WRAP] Running ", join(" ", @cmd), "\n";
    system(@cmd);
    exit 1 unless $? == 0;

    exit 0;
} else {
    my @cmd = ($realitstool, @ARGV);
    print STDERR "# [WRAP] Running ", join(" ", @cmd), "\n";
    exec(@cmd);
}
