#include <factory.idl>
#include <Table.idl>

module GNOME {

	interface Spreadsheet : Table {
		void   set_string (in string text, in long col, in long row)
			raises (OutOfRange);

		string get_string (in long col, in long row)
			raises (OutOfRange);
	};
		
	interface Gnumeric : Spreadsheet {
	};

	interface GnumericFactory : Factory {
	};
};
	
