/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Left section");
gchar *s = N_("Center section:");
gchar *s = N_("Right section:");
gchar *s = N_("Enter the format strings for each section:");
