#ifndef GNUMERIC_WORKBOOK_FORMAT_TOOLBAR_H
#define GNUMERIC_WORKBOOK_FORMAT_TOOLBAR_H

#define TOOLBAR_BOLD_BUTTON_INDEX		2
#define TOOLBAR_ITALIC_BUTTON_INDEX		3
#define TOOLBAR_ALIGN_LEFT_BUTTON_INDEX		4
#define TOOLBAR_ALIGN_CENTER_BUTTON_INDEX	5
#define TOOLBAR_ALIGN_RIGHT_BUTTON_INDEX	6

GtkWidget *workbook_create_format_toolbar (Workbook *wb);

#endif
